class AllText {
  static const String appTitle = "Daily Plans";
  static const String addTask = "Add Task";
  static const String editTask = "Edit Task";
  static const String title = "Title";
  static const String cancel = "Cancel";
  static const String add = "Add";
  static const String save = "Save";
  static const String taskDrawer = "Task Drawer";
  static const String totalTaskColon = "Total Task: ";
  static const String myTasks = "My Tasks";
  static const String bin = "Bin";
  static const String recycleBin = "Recycle Bin";
  static const String tabsScreen = "Tabs Screen";
  static const String pendingTasks = "Pending Tasks";
  static const String pendingTasksColon = "Pending Tasks: ";
  static const String completedTasks = "Completed Tasks";
  static const String completedTasksColon = "Completed Tasks: ";
  static const String favoriteTasks = "Favorite Tasks";
  static const String favoriteTasksColon = "Favorite Tasks: ";
  static const String description = "Description";
  static const String taskName = "Task Name";
  static const String edit = "Edit";
  static const String addToBookMark = "Add to bookmark";
  static const String removeFromBookMark = "Remove from bookmark";
  static const String delete = "Delete";
  static const String permanentlyDelete = "Permanently delete";
  static const String restore = "Restore";
}
